version: '3'

services:
  server:
    build: ./server
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./server:/server
    ports: 
      - 8000:8000
    env_file:
      - .env

  nginx:
    image: nginx:1.19.0-alpine
    restart: unless-stopped
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./client/dist:/var/www/client
    ports:
      - 80:80
    depends_on:
      - server
